import Head from 'next/head'
import Header from '../components/Header'

export default function Speedcubing() {
	const cubingData = [
		{ event: "3x3", single: "6.17", average: "8.95", main: "RS3M 2020" },
		{ event: "3x3 OH", single: "11.55", average: "15.35", main: "Weilong GTS2M" },
		{ event: "3x3 BLD", single: "—", average: "—", main: "—" },
		{ event: "2x2", single: "2.15", average: "3.79", main: "MGC 2x2" },
		{ event: "4x4", single: "34.39", average: "41.49", main: "Aosu WRM" },
		{ event: "5x5", single: "", average: "", main: "Aochuang GTS M" },
		{ event: "6x6", single: "", average: "", main: "MGC 6x6" },
		{ event: "7x7", single: "", average: "", main: "Yufu V2 M" },
		{ event: "Pyraminx", single: "", average: "", main: "Qiyi MS" },
		{ event: "Megaminx", single: "1:03.25", average: "1:25.84", main: "Yuhu V2 M" },
		{ event: "Skewb", single: "", average: "", main: "Aoyan M" },
		{ event: "Square-1", single: "", average: "", main: "Little Magic M" },
		{ event: "Clock", single: "", average: "", main: "Qiyi Clock" },
	]

	return (
		<div>
			<Head>
				<title>Legendary Site | Speedcubing</title>
				<meta name="description" content="Top 10 Site of All Time" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main className="container mt-6 px-4 max-w-3xl mb-24">
				<h1 className="text-5xl font-bold text-center mb-4">
					Speedcubing
				</h1>

				<section className="flex flex-col gap-2 mb-12">
					<p>
						I have been speedcubing on and off as a hobby since 2017. I have only been to 2 WCA competitions, but I would like to go to more.
					</p>
					<a className="text-blue-400 underline" target="_blank" href="https://www.worldcubeassociation.org/persons/2020BOYC01">
						My WCA profile
					</a>
					<p>
						I currently use white cross CFOP for both 2H and OH, but I started practicing color neutral Roux with the hope of switching for OH
						and eventually 2H.
					</p>
				</section>

				<section className="flex flex-col gap-2 mb-12">
					<h1 className="text-2xl font-bold">
						Mains/PBs
					</h1>
					<p>
						These are my best times at home and my main cube for each event.
					</p>
					<div className="flex flex-col divide-y">
						<div className="flex gap-4 font-bold">
							<span className="w-24"></span>
							<span className="w-16">Single</span>
							<span className="w-16">Ao5</span>
							<span>Main cube</span>
						</div>
						{cubingData.map(e => {return (
							<div className="flex gap-4">
								<span className="w-24">{e.event}</span>
								<span className="w-16">{e.single}</span>
								<span className="w-16">{e.average}</span>
								<span>{e.main}</span>
							</div>
						)})}
					</div>
				</section>
				
				<section className="flex flex-col gap-2 mb-12">
					<h1 className="text-2xl font-bold">
						Cubing time standards
					</h1>
					<a className="text-blue-400 underline" target="_blank" href="https://docs.google.com/spreadsheets/d/1CXr5srbXTLxGt1xfzHsR7-RW3tz4P3VB-wK4FLoV1Q4/edit#gid=0">
						2020 Cubing Time Standards
					</a>
					<p>
						I thought it would be helpful to have a way for cubers to track which events they are best and worst in, so I made this spreadsheet.
						Each time standard was generated by multiplying the 16th fastest time in that event from 2020 by some multiplier (x1.1, x1.25, x1.5, etc.),
						meaning that time standards should be roughly comparable between events. For example, I have the 8th standard in 3x3 and 4x4 average but only
						the 6th standard in 5x5, 6x6, and 7x7 average, which suggests that I need to practice big cubes more.
					</p>
				</section>
			</main>
		</div>
	)
}
